[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py createcachetable && python manage.py collectstatic --noinput && python manage.py populate_products && python manage.py populate_units && gunicorn thrifthammer.wsgi --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
